export const liptints = [
  //glossy finish
  {
    name: "peripera ink mood glowy tint",
    shade: "11 brown heaven",
    coverage: "medium",
    finish: "glossy",
    texture: "moist",
    undertone: "warm",
  },
  {
    name: "peripera ink mood glowy tint",
    shade: "03 rose in mind",
    coverage: "medium",
    finish: "glossy",
    texture: "moist",
    undertone: "neutral",
  },
  {
    name: "peripera ink mood glowy tint",
    shade: "10 captivating pink",
    coverage: "medium",
    finish: "glossy",
    texture: "moist",
    undertone: "cool",
  },
  {
    name: "romand dewyful tint",
    shade: "13 custard mauve",
    coverage: "light",
    finish: "glossy",
    texture: "dewy",
    undertone: "cool",
  },
  {
    name: "romand dewyful tint",
    shade: "03 if rose",
    coverage: "light",
    finish: "glossy",
    texture: "dewy",
    undertone: "neutral",
  },
  {
    name: "romand dewyful tint",
    shade: "12 canyon",
    coverage: "light",
    finish: "glossy",
    texture: "dewy",
    undertone: "warm",
  },
  {
    name: "etude glow fixing tint",
    shade: "02 mellow pink",
    coverage: "high",
    finish: "glossy",
    texture: "sticky",
    undertone: "cool",
  },
  {
    name: "etude glow fixing tint",
    shade: "05 mauvement",
    coverage: "high",
    finish: "glossy",
    texture: "sticky",
    undertone: "neutral",
  },
  {
    name: "etude glow fixing tint",
    shade: "03 dewy fig",
    coverage: "high",
    finish: "glossy",
    texture: "sticky",
    undertone: "warm",
  },
  //liquid tint
  {
    name: "peripera ink velvet tint",
    shade: "40 calm rosy",
    coverage: "high",
    finish: "matte",
    texture: "velvet",
    undertone: "cool",
  },
  {
    name: "peripera ink velvet tint",
    shade: "30 classic nude",
    coverage: "high",
    finish: "matte",
    texture: "velvet",
    undertone: "neutral",
  },
  {
    name: "peripera ink velvet tint",
    shade: "25 cinnamon nude",
    coverage: "high",
    finish: "matte",
    texture: "velvet",
    undertone: "warm",
  },
  {
    name: "romand blur fudge tint",
    shade: "01 pomeloco",
    coverage: "medium",
    finish: "matte",
    texture: "fudgy",
    undertone: "warm",
  },
  {
    name: "romand blur fudge tint",
    shade: "02 rosiental",
    coverage: "medium",
    finish: "matte",
    texture: "fudgy",
    undertone: "neutral",
  },
  {
    name: "romand blur fudge tint",
    shade: "07 cool rose up",
    coverage: "medium",
    finish: "matte",
    texture: "fudgy",
    undertone: "cool",
  },
  {
    name: "etude fixing tint",
    shade: "07 cranberry plum",
    coverage: "high",
    finish: "matte",
    texture: "feathery",
    undertone: "cool",
  },
  {
    name: "etude fixing tint",
    shade: "05 midnight mauve",
    coverage: "high",
    finish: "matte",
    texture: "feathery",

    undertone: "neutral",
  },
  {
    name: "etude fixing tint",
    shade: "06 soft walnut",
    coverage: "high",
    finish: "matte",
    texture: "feathery",
    undertone: "warm",
  },
  //balm types
  {
    name: "romand glasting melting balm",
    shade: "05 nougat sand",
    coverage: "light",
    finish: "glossy",
    texture: "balmy",
    undertone: "warm",
  },
  {
    name: "romand glasting melting balm",
    shade: "06 kaya fig",
    coverage: "light",
    finish: "glossy",
    texture: "balmy",
    undertone: "neutral",
  },
  {
    name: "romand glasting melting balm",
    shade: "07 mauve whip",
    coverage: "light",
    finish: "glossy",
    texture: "balmy",
    undertone: "cool",
  },
];

export default liptints;
