const liptints = [
  //glossy finish
  {
    name: "peripera ink mood glowy tint",
    shade: "11 brown heaven",
    coverage: "medium",
    finish: "glossy",
    undertone: "warm",
  },
  {
    name: "peripera ink mood glowy tint",
    shade: "03 rose in mind",
    coverage: "medium",
    finish: "glossy",
    undertone: "neutral",
  },
  {
    name: "peripera ink mood glowy tint",
    shade: "10 captivating pink",
    coverage: "medium",
    finish: "glossy",
    undertone: "cool",
  },
  {
    name: "romand dewyful tint",
    shade: "13 custard mauve",
    coverage: "medium",
    finish: "glossy",
    undertone: "cool",
  },
  {
    name: "romand dewyful tint",
    shade: "03 if rose",
    coverage: "medium",
    finish: "glossy",
    undertone: "neutral",
  },
  {
    name: "romand dewyful tint",
    shade: "12 canyon",
    coverage: "medium",
    finish: "glossy",
    undertone: "warm",
  },
  {
    name: "etude glow fixing tint",
    shade: "mellow pink",
    coverage: "medium",
    finish: "glossy",
    undertone: "cool",
  },
  {
    name: "etude glow fixing tint",
    shade: "mauvement",
    coverage: "medium",
    finish: "glossy",
    undertone: "neutral",
  },
  {
    name: "etude glow fixing tint",
    shade: "dewy fig",
    coverage: "medium",
    finish: "glossy",
    undertone: "warm",
  },
  //liquid tint
  {
    name: "peripera ink velvet tint",
    shade: "FILL IN",
    coverage: "high",
    finish: "matte",
    undertone: "cool",
  },
  {
    name: "peripera ink velvet tint",
    shade: "FILL IN",
    coverage: "high",
    finish: "matte",
    undertone: "neutral",
  },
  {
    name: "peripera ink velvet tint",
    shade: "FILL IN",
    coverage: "high",
    finish: "matte",
    undertone: "warm",
  },
  {
    name: "romand blur fudge tint",
    shade: "FILL IN",
    coverage: "high",
    finish: "matte",
    undertone: "warm",
  },
  {
    name: "romand blur fudge tint",
    shade: "FILL IN",
    coverage: "high",
    finish: "matte",
    undertone: "neutral",
  },
  {
    name: "romand blur fudge tint",
    shade: "FILL IN",
    coverage: "high",
    finish: "matte",
    undertone: "cool",
  },
  {
    name: "etude fixing tint",
    shade: "FILL IN",
    coverage: "high",
    finish: "matte",
    undertone: "cool",
  },
  {
    name: "etude fixing tint",
    shade: "FILL IN",
    coverage: "high",
    finish: "matte",
    undertone: "neutral",
  },
  {
    name: "etude fixing tint",
    shade: "06 soft walnut",
    coverage: "high",
    finish: "matte",
    undertone: "warm",
  },
  //balm types
  {
    name: "romand glasting melting balm",
    shade: "06 soft walnut",
    coverage: "light",
    finish: "glossy",
    undertone: "warm",
  },
];
